<?php
/**
 * ResultadoPesquisaCurriculoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResultadoPesquisaCurriculoTest Class Doc Comment
 *
 * @category    Class */
// * @description ResultadoPesquisaCurriculo
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResultadoPesquisaCurriculoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResultadoPesquisaCurriculo"
     */
    public function testResultadoPesquisaCurriculo()
    {
    }

    /**
     * Test attribute "total_de_registros"
     */
    public function testPropertyTotalDeRegistros()
    {
    }

    /**
     * Test attribute "registros_por_pagina"
     */
    public function testPropertyRegistrosPorPagina()
    {
    }

    /**
     * Test attribute "curriculos"
     */
    public function testPropertyCurriculos()
    {
    }
}
