<?php
/**
 * EnderecoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EnderecoTest Class Doc Comment
 *
 * @category    Class */
// * @description Endereco
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnderecoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Endereco"
     */
    public function testEndereco()
    {
    }

    /**
     * Test attribute "cep"
     */
    public function testPropertyCep()
    {
    }

    /**
     * Test attribute "logradouro"
     */
    public function testPropertyLogradouro()
    {
    }

    /**
     * Test attribute "numero"
     */
    public function testPropertyNumero()
    {
    }

    /**
     * Test attribute "bairro"
     */
    public function testPropertyBairro()
    {
    }

    /**
     * Test attribute "cidade"
     */
    public function testPropertyCidade()
    {
    }

    /**
     * Test attribute "uf"
     */
    public function testPropertyUf()
    {
    }
}
