<?php
/**
 * FormacaoCurriculoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FormacaoCurriculoTest Class Doc Comment
 *
 * @category    Class */
// * @description Classe com as informações de formação
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormacaoCurriculoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FormacaoCurriculo"
     */
    public function testFormacaoCurriculo()
    {
    }

    /**
     * Test attribute "idiomas"
     */
    public function testPropertyIdiomas()
    {
    }

    /**
     * Test attribute "cursos_formacao"
     */
    public function testPropertyCursosFormacao()
    {
    }

    /**
     * Test attribute "cursos_complementares"
     */
    public function testPropertyCursosComplementares()
    {
    }
}
