<?php
/**
 * ResultadoPesquisaVagaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResultadoPesquisaVagaTest Class Doc Comment
 *
 * @category    Class */
// * @description Classe para o retorno de pesquisa de vagas
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResultadoPesquisaVagaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResultadoPesquisaVaga"
     */
    public function testResultadoPesquisaVaga()
    {
    }

    /**
     * Test attribute "registros"
     */
    public function testPropertyRegistros()
    {
    }

    /**
     * Test attribute "facets"
     */
    public function testPropertyFacets()
    {
    }

    /**
     * Test attribute "total_registros"
     */
    public function testPropertyTotalRegistros()
    {
    }

    /**
     * Test attribute "total_paginas"
     */
    public function testPropertyTotalPaginas()
    {
    }

    /**
     * Test attribute "pagina"
     */
    public function testPropertyPagina()
    {
    }

    /**
     * Test attribute "registros_por_pagina"
     */
    public function testPropertyRegistrosPorPagina()
    {
    }
}
