<?php
/**
 * InlineResponse2002ListExperienciaProfissional
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * InlineResponse2002ListExperienciaProfissional Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002ListExperienciaProfissional implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_2_listExperienciaProfissional';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'funcao' => 'string',
        'razao_social' => 'string',
        'descricao_atividade' => 'string',
        'area_bne' => 'string',
        'data_admissao' => '\DateTime',
        'data_demissao' => '\DateTime',
        'vlr_salario' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'funcao' => null,
        'razao_social' => null,
        'descricao_atividade' => null,
        'area_bne' => null,
        'data_admissao' => 'date-time',
        'data_demissao' => 'date-time',
        'vlr_salario' => 'double'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'funcao' => 'Funcao',
        'razao_social' => 'RazaoSocial',
        'descricao_atividade' => 'DescricaoAtividade',
        'area_bne' => 'AreaBNE',
        'data_admissao' => 'DataAdmissao',
        'data_demissao' => 'DataDemissao',
        'vlr_salario' => 'VlrSalario'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'funcao' => 'setFuncao',
        'razao_social' => 'setRazaoSocial',
        'descricao_atividade' => 'setDescricaoAtividade',
        'area_bne' => 'setAreaBne',
        'data_admissao' => 'setDataAdmissao',
        'data_demissao' => 'setDataDemissao',
        'vlr_salario' => 'setVlrSalario'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'funcao' => 'getFuncao',
        'razao_social' => 'getRazaoSocial',
        'descricao_atividade' => 'getDescricaoAtividade',
        'area_bne' => 'getAreaBne',
        'data_admissao' => 'getDataAdmissao',
        'data_demissao' => 'getDataDemissao',
        'vlr_salario' => 'getVlrSalario'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['funcao'] = isset($data['funcao']) ? $data['funcao'] : null;
        $this->container['razao_social'] = isset($data['razao_social']) ? $data['razao_social'] : null;
        $this->container['descricao_atividade'] = isset($data['descricao_atividade']) ? $data['descricao_atividade'] : null;
        $this->container['area_bne'] = isset($data['area_bne']) ? $data['area_bne'] : null;
        $this->container['data_admissao'] = isset($data['data_admissao']) ? $data['data_admissao'] : null;
        $this->container['data_demissao'] = isset($data['data_demissao']) ? $data['data_demissao'] : null;
        $this->container['vlr_salario'] = isset($data['vlr_salario']) ? $data['vlr_salario'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets funcao
     * @return string
     */
    public function getFuncao()
    {
        return $this->container['funcao'];
    }

    /**
     * Sets funcao
     * @param string $funcao
     * @return $this
     */
    public function setFuncao($funcao)
    {
        $this->container['funcao'] = $funcao;

        return $this;
    }

    /**
     * Gets razao_social
     * @return string
     */
    public function getRazaoSocial()
    {
        return $this->container['razao_social'];
    }

    /**
     * Sets razao_social
     * @param string $razao_social
     * @return $this
     */
    public function setRazaoSocial($razao_social)
    {
        $this->container['razao_social'] = $razao_social;

        return $this;
    }

    /**
     * Gets descricao_atividade
     * @return string
     */
    public function getDescricaoAtividade()
    {
        return $this->container['descricao_atividade'];
    }

    /**
     * Sets descricao_atividade
     * @param string $descricao_atividade
     * @return $this
     */
    public function setDescricaoAtividade($descricao_atividade)
    {
        $this->container['descricao_atividade'] = $descricao_atividade;

        return $this;
    }

    /**
     * Gets area_bne
     * @return string
     */
    public function getAreaBne()
    {
        return $this->container['area_bne'];
    }

    /**
     * Sets area_bne
     * @param string $area_bne
     * @return $this
     */
    public function setAreaBne($area_bne)
    {
        $this->container['area_bne'] = $area_bne;

        return $this;
    }

    /**
     * Gets data_admissao
     * @return \DateTime
     */
    public function getDataAdmissao()
    {
        return $this->container['data_admissao'];
    }

    /**
     * Sets data_admissao
     * @param \DateTime $data_admissao
     * @return $this
     */
    public function setDataAdmissao($data_admissao)
    {
        $this->container['data_admissao'] = $data_admissao;

        return $this;
    }

    /**
     * Gets data_demissao
     * @return \DateTime
     */
    public function getDataDemissao()
    {
        return $this->container['data_demissao'];
    }

    /**
     * Sets data_demissao
     * @param \DateTime $data_demissao
     * @return $this
     */
    public function setDataDemissao($data_demissao)
    {
        $this->container['data_demissao'] = $data_demissao;

        return $this;
    }

    /**
     * Gets vlr_salario
     * @return double
     */
    public function getVlrSalario()
    {
        return $this->container['vlr_salario'];
    }

    /**
     * Sets vlr_salario
     * @param double $vlr_salario
     * @return $this
     */
    public function setVlrSalario($vlr_salario)
    {
        $this->container['vlr_salario'] = $vlr_salario;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


