<?php
/**
 * CadastroIdioma
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * CadastroIdioma Class Doc Comment
 *
 * @category    Class
 * @description Classe com as informações do idioma do candidato
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CadastroIdioma implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'CadastroIdioma';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'descricao_idioma' => 'string',
        'nivel_idioma' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'descricao_idioma' => null,
        'nivel_idioma' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'descricao_idioma' => 'DescricaoIdioma',
        'nivel_idioma' => 'NivelIdioma'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'descricao_idioma' => 'setDescricaoIdioma',
        'nivel_idioma' => 'setNivelIdioma'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'descricao_idioma' => 'getDescricaoIdioma',
        'nivel_idioma' => 'getNivelIdioma'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const NIVEL_IDIOMA_BASICO = 'Basico';
    const NIVEL_IDIOMA_INTERMEDIARIO = 'Intermediario';
    const NIVEL_IDIOMA_AVANCADO = 'Avancado';
    const NIVEL_IDIOMA_FLUENTE = 'Fluente';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getNivelIdiomaAllowableValues()
    {
        return [
            self::NIVEL_IDIOMA_BASICO,
            self::NIVEL_IDIOMA_INTERMEDIARIO,
            self::NIVEL_IDIOMA_AVANCADO,
            self::NIVEL_IDIOMA_FLUENTE,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['descricao_idioma'] = isset($data['descricao_idioma']) ? $data['descricao_idioma'] : null;
        $this->container['nivel_idioma'] = isset($data['nivel_idioma']) ? $data['nivel_idioma'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['descricao_idioma'] === null) {
            $invalid_properties[] = "'descricao_idioma' can't be null";
        }
        if ($this->container['nivel_idioma'] === null) {
            $invalid_properties[] = "'nivel_idioma' can't be null";
        }
        $allowed_values = $this->getNivelIdiomaAllowableValues();
        if (!in_array($this->container['nivel_idioma'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'nivel_idioma', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['descricao_idioma'] === null) {
            return false;
        }
        if ($this->container['nivel_idioma'] === null) {
            return false;
        }
        $allowed_values = $this->getNivelIdiomaAllowableValues();
        if (!in_array($this->container['nivel_idioma'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets descricao_idioma
     * @return string
     */
    public function getDescricaoIdioma()
    {
        return $this->container['descricao_idioma'];
    }

    /**
     * Sets descricao_idioma
     * @param string $descricao_idioma Descrição do idioma.  Deve ser um dos valores indicados na tabela Idiomas
     * @return $this
     */
    public function setDescricaoIdioma($descricao_idioma)
    {
        $this->container['descricao_idioma'] = $descricao_idioma;

        return $this;
    }

    /**
     * Gets nivel_idioma
     * @return string
     */
    public function getNivelIdioma()
    {
        return $this->container['nivel_idioma'];
    }

    /**
     * Sets nivel_idioma
     * @param string $nivel_idioma Nível do idioma
     * @return $this
     */
    public function setNivelIdioma($nivel_idioma)
    {
        $allowed_values = $this->getNivelIdiomaAllowableValues();
        if (!in_array($nivel_idioma, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'nivel_idioma', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['nivel_idioma'] = $nivel_idioma;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


