<?php
/**
 * CurriculoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CurriculoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CurriculoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for curriculoDownloadArquivoBycpf
     *
     * .
     *
     */
    public function testCurriculoDownloadArquivoBycpf()
    {
    }

    /**
     * Test case for curriculoGetCadastroCVBycpf
     *
     * Obtem os dados do cadastro do currículo..
     *
     */
    public function testCurriculoGetCadastroCVBycpf()
    {
    }

    /**
     * Test case for curriculoObterCVByIdCurriculoFlgDadosdeContato
     *
     * Retorna o curriculo selecionado pelo usuario a partir do IdCurriculo..
     *
     */
    public function testCurriculoObterCVByIdCurriculoFlgDadosdeContato()
    {
    }

    /**
     * Test case for curriculoObterCVPorCpfBycpfnascimento
     *
     * Retorna o curriculo selecionado pelo usuario a partir do CPF e Data de Nascimento..
     *
     */
    public function testCurriculoObterCVPorCpfBycpfnascimento()
    {
    }

    /**
     * Test case for curriculoObterCadastroCVByIdCurriculoFlgDadosdeContato
     *
     * Retorna o cadastro do curriculo selecionado pelo usuario a partir do IdCurriculo..
     *
     */
    public function testCurriculoObterCadastroCVByIdCurriculoFlgDadosdeContato()
    {
    }

    /**
     * Test case for curriculoPesquisaAvancadaByfiltros
     *
     * Retorna uma lista de currículos baseada nos parâmetros informados..
     *
     */
    public function testCurriculoPesquisaAvancadaByfiltros()
    {
    }

    /**
     * Test case for curriculoPostCadastroCVBycurriculo
     *
     * Cadastra um novo currículo.
     *
     */
    public function testCurriculoPostCadastroCVBycurriculo()
    {
    }

    /**
     * Test case for curriculoPostFotoByfile
     *
     * Atualiza a foto do currículo.
     *
     */
    public function testCurriculoPostFotoByfile()
    {
    }

    /**
     * Test case for curriculoPutCadastroCVBycurriculo
     *
     * Atualiza um currículo.
     *
     */
    public function testCurriculoPutCadastroCVBycurriculo()
    {
    }

    /**
     * Test case for curriculoValidateImageByba
     *
     * Valida o MimeType de uma imagem, ou se consegue abrir o arquivo corretamente usando o objeto Image.
     *
     */
    public function testCurriculoValidateImageByba()
    {
    }
}
