<?php
/**
 * VagasApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * VagasApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VagasApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for vagasAtualizarStatusByidnovoStatusVaga
     *
     * Recupera uma vaga baseada em seu ID.
     *
     */
    public function testVagasAtualizarStatusByidnovoStatusVaga()
    {
    }

    /**
     * Test case for vagasCandidatadasBytipoVinculopaginaregistrosPorPagina
     *
     * Consulta a vagas candidatadas..
     *
     */
    public function testVagasCandidatadasBytipoVinculopaginaregistrosPorPagina()
    {
    }

    /**
     * Test case for vagasCandidatarByidVagacandidatura
     *
     * Realiza a candidatura a uma vaga..
     *
     */
    public function testVagasCandidatarByidVagacandidatura()
    {
    }

    /**
     * Test case for vagasDadosDaEmpresaByidVaga
     *
     * Recupera os dados da empresa que anunciou a vaga.
     *
     */
    public function testVagasDadosDaEmpresaByidVaga()
    {
    }

    /**
     * Test case for vagasGetByid
     *
     * Recupera uma vaga baseada em seu ID.
     *
     */
    public function testVagasGetByid()
    {
    }

    /**
     * Test case for vagasGetBypaginaregistrosPorPaginaquerysalarioMinimosalarioMaximotipoVinculofuncaoareaescolaridadedeficienciadisponibilidadesiglaEstadonomeCidadeempresadataIniciodataFimidOrigemoportunidadeordenacaocursoidCursocurriculoofereceCursofuncaoAgrupadoracidadeRegiaoidfFilialconfidencialcampanhausuarioFilialfacetField
     *
     * Pesquisa de vagas.
     *
     */
    public function testVagasGetBypaginaregistrosPorPaginaquerysalarioMinimosalarioMaximotipoVinculofuncaoareaescolaridadedeficienciadisponibilidadesiglaEstadonomeCidadeempresadataIniciodataFimidOrigemoportunidadeordenacaocursoidCursocurriculoofereceCursofuncaoAgrupadoracidadeRegiaoidfFilialconfidencialcampanhausuarioFilialfacetField()
    {
    }

    /**
     * Test case for vagasGetBypaginaregistrosPorPaginasomenteMinhasVagastipoVinculostatusVaga
     *
     * Recupera a lista de vagas cadastradas para a api key informada.
     *
     */
    public function testVagasGetBypaginaregistrosPorPaginasomenteMinhasVagastipoVinculostatusVaga()
    {
    }

    /**
     * Test case for vagasGetEmpresaByid
     *
     * Recupera uma vaga baseada em seu ID.
     *
     */
    public function testVagasGetEmpresaByid()
    {
    }

    /**
     * Test case for vagasObterCandidatosBycodigoVagapaginareturnType
     *
     * Lista os candidatos de uma determinada vaga..
     *
     */
    public function testVagasObterCandidatosBycodigoVagapaginareturnType()
    {
    }

    /**
     * Test case for vagasObterCurriculosCandidatosBycodigoVagapagina
     *
     * Lista os currículos completos dos candidatos de uma determinada vaga..
     *
     */
    public function testVagasObterCurriculosCandidatosBycodigoVagapagina()
    {
    }

    /**
     * Test case for vagasObterMiniCurriculosCandidatosBycodigoVagapagina
     *
     * Lista os minicurrículos dos candidatos de uma determinada vaga..
     *
     */
    public function testVagasObterMiniCurriculosCandidatosBycodigoVagapagina()
    {
    }

    /**
     * Test case for vagasObterUltimosCandidatosBycodigoVagadatareturnType
     *
     * Lista os candidatos de uma determinada vaga..
     *
     */
    public function testVagasObterUltimosCandidatosBycodigoVagadatareturnType()
    {
    }

    /**
     * Test case for vagasObterUltimosCurriculosCandidatosBycodigoVagadata
     *
     * Lista os currículos candidatos de uma determinada vaga..
     *
     */
    public function testVagasObterUltimosCurriculosCandidatosBycodigoVagadata()
    {
    }

    /**
     * Test case for vagasObterUltimosMiniCurriculosCandidatosBycodigoVagadata
     *
     * Lista os minicurriculos candidatos de uma determinada vaga..
     *
     */
    public function testVagasObterUltimosMiniCurriculosCandidatosBycodigoVagadata()
    {
    }

    /**
     * Test case for vagasSalvarByidVagavaga
     *
     * Atualiza uma vaga já cadastrada..
     *
     */
    public function testVagasSalvarByidVagavaga()
    {
    }

    /**
     * Test case for vagasSalvarByvaga
     *
     * Cadastra uma nova vaga..
     *
     */
    public function testVagasSalvarByvaga()
    {
    }
}
