<?php
/**
 * CursoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CursoTest Class Doc Comment
 *
 * @category    Class */
// * @description Informações sobre o curso de formação do candidato
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CursoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Curso"
     */
    public function testCurso()
    {
    }

    /**
     * Test attribute "nivel_formacao"
     */
    public function testPropertyNivelFormacao()
    {
    }

    /**
     * Test attribute "instituicao"
     */
    public function testPropertyInstituicao()
    {
    }

    /**
     * Test attribute "nome_curso"
     */
    public function testPropertyNomeCurso()
    {
    }

    /**
     * Test attribute "cidade"
     */
    public function testPropertyCidade()
    {
    }

    /**
     * Test attribute "ano_de_conclusao"
     */
    public function testPropertyAnoDeConclusao()
    {
    }

    /**
     * Test attribute "situacao"
     */
    public function testPropertySituacao()
    {
    }

    /**
     * Test attribute "periodo"
     */
    public function testPropertyPeriodo()
    {
    }
}
