<?php
/**
 * EmpresaSelecionadoraTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmpresaSelecionadoraTest Class Doc Comment
 *
 * @category    Class */
// * @description EmpresaSelecionadora
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmpresaSelecionadoraTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmpresaSelecionadora"
     */
    public function testEmpresaSelecionadora()
    {
    }

    /**
     * Test attribute "cnpj"
     */
    public function testPropertyCnpj()
    {
    }

    /**
     * Test attribute "razao_social"
     */
    public function testPropertyRazaoSocial()
    {
    }

    /**
     * Test attribute "nome_fantasia"
     */
    public function testPropertyNomeFantasia()
    {
    }

    /**
     * Test attribute "matriz"
     */
    public function testPropertyMatriz()
    {
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "ddd_telefone"
     */
    public function testPropertyDddTelefone()
    {
    }

    /**
     * Test attribute "num_telefone"
     */
    public function testPropertyNumTelefone()
    {
    }

    /**
     * Test attribute "endereco"
     */
    public function testPropertyEndereco()
    {
    }
}
