<?php
/**
 * FormacaoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FormacaoTest Class Doc Comment
 *
 * @category    Class */
// * @description Formacao
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormacaoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Formacao"
     */
    public function testFormacao()
    {
    }

    /**
     * Test attribute "descricao_formacao"
     */
    public function testPropertyDescricaoFormacao()
    {
    }

    /**
     * Test attribute "descricao_curso"
     */
    public function testPropertyDescricaoCurso()
    {
    }

    /**
     * Test attribute "nome_fonte"
     */
    public function testPropertyNomeFonte()
    {
    }

    /**
     * Test attribute "sigla_fonte"
     */
    public function testPropertySiglaFonte()
    {
    }

    /**
     * Test attribute "situacao_formacao"
     */
    public function testPropertySituacaoFormacao()
    {
    }

    /**
     * Test attribute "ano_conclusao"
     */
    public function testPropertyAnoConclusao()
    {
    }

    /**
     * Test attribute "periodo"
     */
    public function testPropertyPeriodo()
    {
    }
}
