<?php
/**
 * InlineResponse200MiniCurriculoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200MiniCurriculoTest Class Doc Comment
 *
 * @category    Class */
// * @description Informações mínimas para um currículo
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200MiniCurriculoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200MiniCurriculo"
     */
    public function testInlineResponse200MiniCurriculo()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "cpf"
     */
    public function testPropertyCpf()
    {
    }

    /**
     * Test attribute "data_nascimento"
     */
    public function testPropertyDataNascimento()
    {
    }

    /**
     * Test attribute "ddd_celular"
     */
    public function testPropertyDddCelular()
    {
    }

    /**
     * Test attribute "numero_celular"
     */
    public function testPropertyNumeroCelular()
    {
    }

    /**
     * Test attribute "nome"
     */
    public function testPropertyNome()
    {
    }

    /**
     * Test attribute "sexo"
     */
    public function testPropertySexo()
    {
    }

    /**
     * Test attribute "cidade"
     */
    public function testPropertyCidade()
    {
    }

    /**
     * Test attribute "escolaridade"
     */
    public function testPropertyEscolaridade()
    {
    }

    /**
     * Test attribute "aceito_estagio"
     */
    public function testPropertyAceitoEstagio()
    {
    }

    /**
     * Test attribute "funcoes_pretendidas"
     */
    public function testPropertyFuncoesPretendidas()
    {
    }

    /**
     * Test attribute "pretensao_salarial"
     */
    public function testPropertyPretensaoSalarial()
    {
    }
}
