<?php
/**
 * InlineResponse2007Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2007Test Class Doc Comment
 *
 * @category    Class */
// * @description Dados da empresa
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2007Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2007"
     */
    public function testInlineResponse2007()
    {
    }

    /**
     * Test attribute "nome_empresa"
     */
    public function testPropertyNomeEmpresa()
    {
    }

    /**
     * Test attribute "quantidade_funcionarios"
     */
    public function testPropertyQuantidadeFuncionarios()
    {
    }

    /**
     * Test attribute "numero_telefone"
     */
    public function testPropertyNumeroTelefone()
    {
    }

    /**
     * Test attribute "cidade"
     */
    public function testPropertyCidade()
    {
    }

    /**
     * Test attribute "bairro"
     */
    public function testPropertyBairro()
    {
    }

    /**
     * Test attribute "data_cadastro"
     */
    public function testPropertyDataCadastro()
    {
    }

    /**
     * Test attribute "quantidade_vagas_divulgadas"
     */
    public function testPropertyQuantidadeVagasDivulgadas()
    {
    }

    /**
     * Test attribute "numero_cnpj"
     */
    public function testPropertyNumeroCnpj()
    {
    }

    /**
     * Test attribute "des_area_bne"
     */
    public function testPropertyDesAreaBne()
    {
    }
}
