<?php
/**
 * Vaga1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Vaga1Test Class Doc Comment
 *
 * @category    Class */
// * @description Representa uma vaga de emprego no BNE com informações extras que devem ser exibidas somente para a empresa anunciante.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Vaga1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Vaga1"
     */
    public function testVaga1()
    {
    }

    /**
     * Test attribute "idade_min"
     */
    public function testPropertyIdadeMin()
    {
    }

    /**
     * Test attribute "idade_max"
     */
    public function testPropertyIdadeMax()
    {
    }

    /**
     * Test attribute "sexo"
     */
    public function testPropertySexo()
    {
    }

    /**
     * Test attribute "num_ddd"
     */
    public function testPropertyNumDdd()
    {
    }

    /**
     * Test attribute "telefone"
     */
    public function testPropertyTelefone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "receber_cada_cv"
     */
    public function testPropertyReceberCadaCv()
    {
    }

    /**
     * Test attribute "receber_todos_cv"
     */
    public function testPropertyReceberTodosCv()
    {
    }

    /**
     * Test attribute "perguntas"
     */
    public function testPropertyPerguntas()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "tipo_vinculo"
     */
    public function testPropertyTipoVinculo()
    {
    }

    /**
     * Test attribute "cursos"
     */
    public function testPropertyCursos()
    {
    }

    /**
     * Test attribute "funcao"
     */
    public function testPropertyFuncao()
    {
    }

    /**
     * Test attribute "cidade"
     */
    public function testPropertyCidade()
    {
    }

    /**
     * Test attribute "quantidade"
     */
    public function testPropertyQuantidade()
    {
    }

    /**
     * Test attribute "escolaridade"
     */
    public function testPropertyEscolaridade()
    {
    }

    /**
     * Test attribute "salario_min"
     */
    public function testPropertySalarioMin()
    {
    }

    /**
     * Test attribute "salario_max"
     */
    public function testPropertySalarioMax()
    {
    }

    /**
     * Test attribute "beneficios"
     */
    public function testPropertyBeneficios()
    {
    }

    /**
     * Test attribute "requisitos"
     */
    public function testPropertyRequisitos()
    {
    }

    /**
     * Test attribute "atribuicoes"
     */
    public function testPropertyAtribuicoes()
    {
    }

    /**
     * Test attribute "disponibilidade"
     */
    public function testPropertyDisponibilidade()
    {
    }

    /**
     * Test attribute "nome_fantasia"
     */
    public function testPropertyNomeFantasia()
    {
    }

    /**
     * Test attribute "confidencial"
     */
    public function testPropertyConfidencial()
    {
    }

    /**
     * Test attribute "deficiencia"
     */
    public function testPropertyDeficiencia()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "data_cadastro"
     */
    public function testPropertyDataCadastro()
    {
    }

    /**
     * Test attribute "sigla_estado"
     */
    public function testPropertySiglaEstado()
    {
    }

    /**
     * Test attribute "data_anuncio"
     */
    public function testPropertyDataAnuncio()
    {
    }

    /**
     * Test attribute "des_origem"
     */
    public function testPropertyDesOrigem()
    {
    }

    /**
     * Test attribute "tipo_origem"
     */
    public function testPropertyTipoOrigem()
    {
    }

    /**
     * Test attribute "bne_recomenda"
     */
    public function testPropertyBneRecomenda()
    {
    }

    /**
     * Test attribute "codigo_vaga"
     */
    public function testPropertyCodigoVaga()
    {
    }

    /**
     * Test attribute "id_filial"
     */
    public function testPropertyIdFilial()
    {
    }

    /**
     * Test attribute "bairro"
     */
    public function testPropertyBairro()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "plano"
     */
    public function testPropertyPlano()
    {
    }

    /**
     * Test attribute "oferece_cursos"
     */
    public function testPropertyOfereceCursos()
    {
    }

    /**
     * Test attribute "campanha"
     */
    public function testPropertyCampanha()
    {
    }
}
