<?php
/**
 * InlineResponse200ExperienciasTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse200ExperienciasTest Class Doc Comment
 *
 * @category    Class */
// * @description Classe com as informações de experiências profissionais
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200ExperienciasTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200Experiencias"
     */
    public function testInlineResponse200Experiencias()
    {
    }

    /**
     * Test attribute "nome_empresa"
     */
    public function testPropertyNomeEmpresa()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "data_admissao"
     */
    public function testPropertyDataAdmissao()
    {
    }

    /**
     * Test attribute "data_demissao"
     */
    public function testPropertyDataDemissao()
    {
    }

    /**
     * Test attribute "funcao"
     */
    public function testPropertyFuncao()
    {
    }

    /**
     * Test attribute "atribuicoes"
     */
    public function testPropertyAtribuicoes()
    {
    }

    /**
     * Test attribute "salario"
     */
    public function testPropertySalario()
    {
    }
}
