<?php
/**
 * InlineResponse2004Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2004Test Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2004
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2004Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2004"
     */
    public function testInlineResponse2004()
    {
    }

    /**
     * Test attribute "id_pessoa"
     */
    public function testPropertyIdPessoa()
    {
    }

    /**
     * Test attribute "cpf"
     */
    public function testPropertyCpf()
    {
    }

    /**
     * Test attribute "nome"
     */
    public function testPropertyNome()
    {
    }

    /**
     * Test attribute "sexo"
     */
    public function testPropertySexo()
    {
    }

    /**
     * Test attribute "nascimento"
     */
    public function testPropertyNascimento()
    {
    }

    /**
     * Test attribute "ddd_celular"
     */
    public function testPropertyDddCelular()
    {
    }

    /**
     * Test attribute "num_celular"
     */
    public function testPropertyNumCelular()
    {
    }

    /**
     * Test attribute "ddd_telefone"
     */
    public function testPropertyDddTelefone()
    {
    }

    /**
     * Test attribute "num_telefone"
     */
    public function testPropertyNumTelefone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "empresas"
     */
    public function testPropertyEmpresas()
    {
    }
}
