<?php
/**
 * InlineResponse2002Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2002Test Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2002
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002"
     */
    public function testInlineResponse2002()
    {
    }

    /**
     * Test attribute "foto"
     */
    public function testPropertyFoto()
    {
    }

    /**
     * Test attribute "vip"
     */
    public function testPropertyVip()
    {
    }

    /**
     * Test attribute "cpf"
     */
    public function testPropertyCpf()
    {
    }

    /**
     * Test attribute "dta_atualizacao"
     */
    public function testPropertyDtaAtualizacao()
    {
    }

    /**
     * Test attribute "dta_nascimento"
     */
    public function testPropertyDtaNascimento()
    {
    }

    /**
     * Test attribute "ddd_celular"
     */
    public function testPropertyDddCelular()
    {
    }

    /**
     * Test attribute "num_celular"
     */
    public function testPropertyNumCelular()
    {
    }

    /**
     * Test attribute "ddd_telefone"
     */
    public function testPropertyDddTelefone()
    {
    }

    /**
     * Test attribute "num_telefone"
     */
    public function testPropertyNumTelefone()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "nome_completo"
     */
    public function testPropertyNomeCompleto()
    {
    }

    /**
     * Test attribute "sexo"
     */
    public function testPropertySexo()
    {
    }

    /**
     * Test attribute "estado_civil"
     */
    public function testPropertyEstadoCivil()
    {
    }

    /**
     * Test attribute "idade"
     */
    public function testPropertyIdade()
    {
    }

    /**
     * Test attribute "funcoes"
     */
    public function testPropertyFuncoes()
    {
    }

    /**
     * Test attribute "pretensao"
     */
    public function testPropertyPretensao()
    {
    }

    /**
     * Test attribute "escolaridade"
     */
    public function testPropertyEscolaridade()
    {
    }

    /**
     * Test attribute "observacoes"
     */
    public function testPropertyObservacoes()
    {
    }

    /**
     * Test attribute "aceita_estagio"
     */
    public function testPropertyAceitaEstagio()
    {
    }

    /**
     * Test attribute "cep_endereco"
     */
    public function testPropertyCepEndereco()
    {
    }

    /**
     * Test attribute "logradouro_endereco"
     */
    public function testPropertyLogradouroEndereco()
    {
    }

    /**
     * Test attribute "numero_endereco"
     */
    public function testPropertyNumeroEndereco()
    {
    }

    /**
     * Test attribute "complemento_endereco"
     */
    public function testPropertyComplementoEndereco()
    {
    }

    /**
     * Test attribute "bairro_endereco"
     */
    public function testPropertyBairroEndereco()
    {
    }

    /**
     * Test attribute "cidade"
     */
    public function testPropertyCidade()
    {
    }

    /**
     * Test attribute "estado"
     */
    public function testPropertyEstado()
    {
    }

    /**
     * Test attribute "carteira"
     */
    public function testPropertyCarteira()
    {
    }

    /**
     * Test attribute "id_curriculo"
     */
    public function testPropertyIdCurriculo()
    {
    }

    /**
     * Test attribute "numero_rg"
     */
    public function testPropertyNumeroRg()
    {
    }

    /**
     * Test attribute "orgao_expeditor"
     */
    public function testPropertyOrgaoExpeditor()
    {
    }

    /**
     * Test attribute "deficiente"
     */
    public function testPropertyDeficiente()
    {
    }

    /**
     * Test attribute "caracteristicas_pessoais"
     */
    public function testPropertyCaracteristicasPessoais()
    {
    }

    /**
     * Test attribute "outros_conhecimento"
     */
    public function testPropertyOutrosConhecimento()
    {
    }

    /**
     * Test attribute "flag_viagem"
     */
    public function testPropertyFlagViagem()
    {
    }

    /**
     * Test attribute "list_experiencia_profissional"
     */
    public function testPropertyListExperienciaProfissional()
    {
    }

    /**
     * Test attribute "idiomas"
     */
    public function testPropertyIdiomas()
    {
    }

    /**
     * Test attribute "formacoes"
     */
    public function testPropertyFormacoes()
    {
    }

    /**
     * Test attribute "data_hora_candidatura"
     */
    public function testPropertyDataHoraCandidatura()
    {
    }
}
