<?php
/**
 * QueryVagasTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QueryVagasTest Class Doc Comment
 *
 * @category    Class */
// * @description Parâmetros para a pesquisa de vaga
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QueryVagasTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QueryVagas"
     */
    public function testQueryVagas()
    {
    }

    /**
     * Test attribute "pagina"
     */
    public function testPropertyPagina()
    {
    }

    /**
     * Test attribute "registros_por_pagina"
     */
    public function testPropertyRegistrosPorPagina()
    {
    }

    /**
     * Test attribute "query"
     */
    public function testPropertyQuery()
    {
    }

    /**
     * Test attribute "salario_minimo"
     */
    public function testPropertySalarioMinimo()
    {
    }

    /**
     * Test attribute "salario_maximo"
     */
    public function testPropertySalarioMaximo()
    {
    }

    /**
     * Test attribute "tipo_vinculo"
     */
    public function testPropertyTipoVinculo()
    {
    }

    /**
     * Test attribute "funcao"
     */
    public function testPropertyFuncao()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "escolaridade"
     */
    public function testPropertyEscolaridade()
    {
    }

    /**
     * Test attribute "deficiencia"
     */
    public function testPropertyDeficiencia()
    {
    }

    /**
     * Test attribute "disponibilidade"
     */
    public function testPropertyDisponibilidade()
    {
    }

    /**
     * Test attribute "sigla_estado"
     */
    public function testPropertySiglaEstado()
    {
    }

    /**
     * Test attribute "nome_cidade"
     */
    public function testPropertyNomeCidade()
    {
    }

    /**
     * Test attribute "empresa"
     */
    public function testPropertyEmpresa()
    {
    }

    /**
     * Test attribute "data_inicio"
     */
    public function testPropertyDataInicio()
    {
    }

    /**
     * Test attribute "data_fim"
     */
    public function testPropertyDataFim()
    {
    }

    /**
     * Test attribute "id_origem"
     */
    public function testPropertyIdOrigem()
    {
    }

    /**
     * Test attribute "oportunidade"
     */
    public function testPropertyOportunidade()
    {
    }

    /**
     * Test attribute "ordenacao"
     */
    public function testPropertyOrdenacao()
    {
    }

    /**
     * Test attribute "curso"
     */
    public function testPropertyCurso()
    {
    }

    /**
     * Test attribute "id_curso"
     */
    public function testPropertyIdCurso()
    {
    }

    /**
     * Test attribute "curriculo"
     */
    public function testPropertyCurriculo()
    {
    }

    /**
     * Test attribute "oferece_curso"
     */
    public function testPropertyOfereceCurso()
    {
    }

    /**
     * Test attribute "funcao_agrupadora"
     */
    public function testPropertyFuncaoAgrupadora()
    {
    }

    /**
     * Test attribute "cidade_regiao"
     */
    public function testPropertyCidadeRegiao()
    {
    }

    /**
     * Test attribute "idf_filial"
     */
    public function testPropertyIdfFilial()
    {
    }

    /**
     * Test attribute "confidencial"
     */
    public function testPropertyConfidencial()
    {
    }

    /**
     * Test attribute "campanha"
     */
    public function testPropertyCampanha()
    {
    }

    /**
     * Test attribute "usuario_filial"
     */
    public function testPropertyUsuarioFilial()
    {
    }

    /**
     * Test attribute "facet_field"
     */
    public function testPropertyFacetField()
    {
    }
}
