<?php
/**
 * V10CurriculoPesquisaAvancadaFormacaoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V10CurriculoPesquisaAvancadaFormacaoTest Class Doc Comment
 *
 * @category    Class */
// * @description Parametros de pesquisa para formacoes
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V10CurriculoPesquisaAvancadaFormacaoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V10CurriculoPesquisaAvancadaFormacao"
     */
    public function testV10CurriculoPesquisaAvancadaFormacao()
    {
    }

    /**
     * Test attribute "escolaridade"
     */
    public function testPropertyEscolaridade()
    {
    }

    /**
     * Test attribute "curso"
     */
    public function testPropertyCurso()
    {
    }

    /**
     * Test attribute "instituicao"
     */
    public function testPropertyInstituicao()
    {
    }

    /**
     * Test attribute "ano_conclusao"
     */
    public function testPropertyAnoConclusao()
    {
    }

    /**
     * Test attribute "periodo"
     */
    public function testPropertyPeriodo()
    {
    }

    /**
     * Test attribute "situacao_curso"
     */
    public function testPropertySituacaoCurso()
    {
    }

    /**
     * Test attribute "cidade"
     */
    public function testPropertyCidade()
    {
    }
}
