<?php
/**
 * TabelasApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TabelasApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TabelasApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for tabelasAreas
     *
     * Lista de áreas.
     *
     */
    public function testTabelasAreas()
    {
    }

    /**
     * Test case for tabelasCategoriasHabilitacao
     *
     * Lista de Categorias de Habilitação.
     *
     */
    public function testTabelasCategoriasHabilitacao()
    {
    }

    /**
     * Test case for tabelasCidadesBynomeParcialnumeroRegistros
     *
     * Lista de Cidades.
     *
     */
    public function testTabelasCidadesBynomeParcialnumeroRegistros()
    {
    }

    /**
     * Test case for tabelasCursosBynomeParcialnumeroRegistros
     *
     * Lista de cursos..
     *
     */
    public function testTabelasCursosBynomeParcialnumeroRegistros()
    {
    }

    /**
     * Test case for tabelasDeficiencias
     *
     * Lista de Deficiências.
     *
     */
    public function testTabelasDeficiencias()
    {
    }

    /**
     * Test case for tabelasEscolaridades
     *
     * Lista de Escolaridades.
     *
     */
    public function testTabelasEscolaridades()
    {
    }

    /**
     * Test case for tabelasEstadosCivis
     *
     * Lista de Estados Civis.
     *
     */
    public function testTabelasEstadosCivis()
    {
    }

    /**
     * Test case for tabelasFuncoesBynomeParcialnumeroRegistros
     *
     * Lista de funções..
     *
     */
    public function testTabelasFuncoesBynomeParcialnumeroRegistros()
    {
    }

    /**
     * Test case for tabelasIdiomas
     *
     * Lista de Idiomas.
     *
     */
    public function testTabelasIdiomas()
    {
    }

    /**
     * Test case for tabelasInstituicoesBynomeParcialnivelCursonumeroRegistros
     *
     * Instituições de insino..
     *
     */
    public function testTabelasInstituicoesBynomeParcialnivelCursonumeroRegistros()
    {
    }

    /**
     * Test case for tabelasRacas
     *
     * Lista de Raças.
     *
     */
    public function testTabelasRacas()
    {
    }

    /**
     * Test case for tabelasTiposVeiculos
     *
     * Lista de Tipos de Veículo.
     *
     */
    public function testTabelasTiposVeiculos()
    {
    }
}
